name: SFTP Deploy
permissions:
  contents: read
  pull-requests: write
  deployments: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download blazor artifact
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: blazor
        workflow: dotnet.yml
    - name: Download api artifact
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: blazor
        workflow: dotnet.yml        
    - name: List files
      run: ls -R