name: SFTP Deploy
permissions:
  contents: read
  pull-requests: write
  deployments: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download blazor artifact
      uses: actions/download-artifact@v4
      with:
        name: blazor
        workflow: .NET 
    - name: List files
      run: ls -R